SAVE_FOLDER = './storage/succession/initial_version'
TEST_FOLDER = './storage/succession/test_version'

# TEST_FOLDER = './storage/succession/saving/chatglm_128k_1'
# TEST_FOLDER = './storage/succession/saving/chatglm_64k_1'
# TEST_FOLDER = './storage/succession/saving/chatglm_1'
# TEST_FOLDER = './storage/succession/saving/llama2_1'
# TEST_FOLDER = './storage/succession/saving/mistral_1'
# TEST_FOLDER = './storage/succession/saving/falcon_1'
# SAVE_FOLDER = TEST_FOLDER
LOG_FOLDER = './logs'
INPUT_FOLDER = './storage/succession/inputs'

model_cache_dir = 'cache_folder'
if 'llama2' in TEST_FOLDER:
    model_cache_dir = 'cache_folder/models--meta-llama--Llama-2-7b-chat-hf/snapshots/9eae4b460bfc40df6c741e67d9634f963b31e02e'

debug = False

MIN_SUPPORT_RELATION_SCORE = 20

PRIVATE_CHAT_ROUND = 3
MEETING_CHAT_ROUND = 3
GROUP_CHAT_ROUND = 3
GAME_ROUND = 3

INITIAL_RELATION_SCORE = 10
MAX_RELATION_SCORE_CHANGE = 10
MAX_RELATION_SCORE = 100
MIN_RELATION_SCORE = 0
MAX_BELIEF_SCORE_CHANGE = 10
MIN_BELIEF_SCORE = 0
MAX_BELIEF_SCORE = 100

INITIAL_INFLUENCE_SCORE = 0
MAX_INFLUENCE_SCORE_CHANGE = 30
MAX_INFLUENCE_SCORE = 9999
MIN_INFLUENCE_SCORE = 0

MAX_MEMORY_RETRIEVE_IN_PERCEIVE = 20
MAX_MEMORY_RETRIEVE_IN_REFLECT = 999

ERROR_RETRY_TIMES = 10

ACTIONHISTORY_VOTE = 30
ACTIONHISTORY_NONVOTE = 20
ACTIONHISTORY_RETRIEVE_NUM = 10

ACTIONHISTORY_RETRIEVE_NUM_ANNOUNCEMENT = 20
ACTIONHISTORY_RETRIEVE_NUM_COMPETE = 20
ACTIONHISTORY_RETRIEVE_NUM_COLLABORATE = 20
ACTIONHISTORY_RETRIEVE_NUM_UPDATE = 30
ACTIONHISTORY_RETRIEVE_NUM_WHOLE_INFORMATION = 30
ACTIONHISTORY_RETRIEVE_NUM_PARTIAL_INFORMATION = 30


# ACTIONHISTORY_VOTE = 0
# ACTIONHISTORY_NONVOTE = 0
# ACTIONHISTORY_RETRIEVE_NUM = 0
# ACTIONHISTORY_RETRIEVE_NUM_ANNOUNCEMENT = 0
# ACTIONHISTORY_RETRIEVE_NUM_COMPETE = 0
# ACTIONHISTORY_RETRIEVE_NUM_COLLABORATE = 0
# ACTIONHISTORY_RETRIEVE_NUM_UPDATE = 0
# ACTIONHISTORY_RETRIEVE_NUM_WHOLE_INFORMATION = 30
# ACTIONHISTORY_RETRIEVE_NUM_PARTIAL_INFORMATION = 30
